#!/bin/sh
set -e
package_name=biglinux-multi-kde
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/xsessions/plasma.desktop"
    dpkg-divert --package "$package_name" --rename --remove "/usr/bin/ksplashqml"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/xsessions/plasma.desktop"
    dpkg-divert --package "$package_name" --rename --remove "/usr/bin/ksplashqml"
;;
esac
exit 0
